sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      dist: xenial
      env: TOXENV=py37

    - python: 3.7
      dist: xenial
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox


jobs:
  include:
    - stage: docker
      language: minimal
      install:
        # test docker build
        - docker build -t habapp .
        - docker run -d --name habapp habapp
      script:
        - sleep 5
        # output stdout to travis
        - docker logs habapp
        # Test docker is still running
        - docker ps | grep -q habapp