sudo: false

jobs:
  include:
    - &python_37
      language: python
      python: 3.7
      script: tox
      install: pip install tox
      env: TOXENV=py37

    - <<: *python_37
      python: 3.6
      env: TOXENV=py36

    - <<: *python_37
      env: TOXENV=flake

    - <<: *python_37
      python: 3.7
      env: TOXENV=docs

    - stage: docker
      language: minimal
      install:
        # test docker build
        - docker build -t habapp .
        - docker run -d --name habapp habapp
      script:
        - sleep 5
        # output stdout to travis
        - docker logs habapp
        # Test docker is still running
        - docker ps | grep -q habapp