sudo: false

jobs:
  include:
    - &python_shared
      language: python
      script: tox
      install: pip install tox

    - <<: *python_shared
      python: 3.6
      env: TOXENV=flake

    - <<: *python_shared
      python: 3.6
      env: TOXENV=py36

    - <<: *python_shared
      python: 3.7
      dist: xenial
      env: TOXENV=py37

    - <<: *python_shared
      python: 3.7
      dist: xenial
      env: TOXENV=docs

    - stage: docker
      language: minimal
      install:
        # test docker build
        - docker build -t habapp .
        - docker run -d --name habapp habapp
      script:
        - sleep 5
        # output stdout to travis
        - docker logs habapp
        # Test docker is still running
        - docker ps | grep -q habapp