sudo: false
language: python

services:
  - docker

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      dist: xenial
      env: TOXENV=py37

    - python: 3.7
      dist: xenial
      env: TOXENV=docs

    - docker:
        install:
          # test docker build
          - docker build -t habapp .
          - docker run -d --name habapp habapp
        script:
          # Test docker is still running
          - docker ps | grep -q habapp

install:
  - pip install tox

script:
  - tox
