ping:
  enabled : True
  item : Ping

directories:
  logging : 'log'
  rules   : 'rules'

connection:
  host: localhost
  port: 8080
#  user: 'test'
#  pass: 'asfd'

timezone: '+0100'

async timeout: 10

